# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GonCgsu1efVMgJe0p0bqJv_PnAL5hJak
"""

import os
import pickle
from datetime import datetime
from typing import List

import numpy as np
import pandas as pd
from fastapi import FastAPI
from loguru import logger

from database import postgres_connection
from schema import PostGet


# === Вспомогательные функции ===
def load_sql(query: str) -> pd.DataFrame:
    conn = postgres_connection()
    try:
        df = pd.read_sql(query, conn)
    except Exception as e:
        raise RuntimeError(f"❌ Ошибка при выполнении SQL-запроса: {e}\nЗапрос: {query}") from e
    finally:
        conn.close()
    return df


def load_model(model_path: str = "model.pkl"):
    if os.environ.get("IS_LMS", "0") == "1":
        model_path = os.environ["MODEL_PATH"]

    logger.info(f"Загрузка модели из файла {model_path}...")
    try:
        with open(model_path, "rb") as file:
            model = pickle.load(file)
    except FileNotFoundError:
        raise FileNotFoundError(f"❌ Файл модели не найден: {model_path}")
    except Exception as e:
        raise RuntimeError(f"❌ Ошибка при загрузке модели: {e}") from e

    logger.success("Модель успешно загружена")
    return model


def extract_time_features(dt: datetime) -> dict:
    hour = dt.hour
    day_of_week = dt.weekday()
    month = dt.month

    hour_sin = np.sin(2 * np.pi * hour / 24)
    hour_cos = np.cos(2 * np.pi * hour / 24)
    dow_sin = np.sin(2 * np.pi * day_of_week / 7)
    dow_cos = np.cos(2 * np.pi * day_of_week / 7)


    return {
        'hour_of_day': hour,
        'day_of_week': day_of_week,
        'month': month,
        'hour_sin': hour_sin,
        'hour_cos': hour_cos,
        'dow_sin': dow_sin,
        'dow_cos': dow_cos
    }


# === Загрузка основных ресурсов ===
logger.info("Инициализация сервиса...")
app = FastAPI()

# Модель
model = load_model()

# Признаки пользователей
logger.info("Загрузка признаков пользователей...")
user_features = load_sql("SELECT * FROM andr_iv7_user_features")
user_features = user_features.set_index('user_id')
logger.info(f"Загружено {len(user_features)} пользователей")

# Числовые признаки постов (все, кроме text/topic)
logger.info("Загрузка числовых признаков постов...")
post_features = load_sql("SELECT * FROM andr_iv7_post_features")
post_features = post_features.set_index('post_id')
logger.info(f"Загружено {len(post_features)} постов с признаками")

# Тексты и темы постов (из исходной таблицы)
logger.info("Загрузка текстов и тем постов...")
post_texts = load_sql("SELECT post_id, text, topic FROM post_text_df")
post_texts = post_texts.set_index('post_id')
logger.info(f"Загружено {len(post_texts)} текстов")

# Ожидаемые признаки модели
if hasattr(model, 'feature_names_in_'):
    expected_features = list(model.feature_names_in_)
    logger.info(f"Модель ожидает {len(expected_features)} признаков")
else:
    expected_features = None
    logger.warning("Не удалось получить список фичей модели")


logger.success("Сервис успешно инициализирован")


@app.get("/post/recommendations/", response_model=List[PostGet])
def recommended_posts(user_id: int, dt: datetime, limit: int = 10) -> List[PostGet]:
    # Признаки пользователя
    if user_id in user_features.index:
        user_row = user_features.loc[user_id].to_dict()
    else:
        user_row = user_features.mean().to_dict()

    # Временные признаки
    time_features = extract_time_features(dt)

    # Формируем матрицу X для всех постов
    X = post_features.copy()
    for col, val in user_row.items():
        X[col] = val
    for col, val in time_features.items():
        X[col] = val

    # Упорядочиваем колонки
    if expected_features is not None:
        missing = set(expected_features) - set(X.columns)
        if missing:
            for col in missing:
                X[col] = 0
        X = X[expected_features]

    # Предсказания
    proba = model.predict_proba(X)[:, 1]
    X['proba'] = proba

    # Топ-limit
    top_posts = X.nlargest(limit, 'proba')

    # Формируем ответ, беря текст и тему из post_texts
    recs = []
    for post_id, row in top_posts.iterrows():
        text_row = post_texts.loc[post_id]
        recs.append(PostGet(id=post_id, text=text_row['text'], topic=text_row['topic']))

    return recs