# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AI-C_lrHe-VTJwGGHA_IMh3Lav84HWBK
"""

from psycopg2.extras import DictCursor
from database import postgres_connection
from typing import List, Optional
from psycopg2.extensions import connection

from models import User, Post, Feed

def get_user(conn: connection, user_id: int) -> Optional[User]:
    """
    Загружает одного пользователя из базы данных по его Id.

    Возвращает объект User, если пользователь найден.
    Если пользователь с таким id отсутствует — возвращает None.
    """
    # TODO: Написать SQL-запрос для получения пользователя по user_id
    query = "select id, gender, age, country, city, exp_group, os, source from public.user where id = %s" #WHERE id = %s — безопасный способ отфильтровать строки по id, где %s служит маркером для подстановки значения из кода


    with conn.cursor(cursor_factory=DictCursor) as cur:
        cur.execute(query, (user_id,)) #Запись (user_id,) — это кортеж (tuple) в Python, содержащий одно значение user_id.
        #Метод cur.execute(query, params) из psycopg2 ожидает второй аргумент в виде последовательности (list, tuple, dict и т. п.), содержащей значения для подстановки в запрос (%s).
        row = cur.fetchone()

        # TODO: Преобразовать результат в объект User, если строка найдена
        if row is not None:
            return User(**row)
        return None


def get_post(conn: connection, post_id: int) -> Optional[Post]:
    """
    Загружает один пост из базы данных по его Id.

    Возвращает объект Post, если пост найден.
    Если пост с таким id отсутствует — возвращает None.
    """
    # TODO: Написать SQL-запрос для получения поста по post_id
    query = "select id,text,topic from public.post where id = %s"

    with conn.cursor(cursor_factory=DictCursor) as cur:
        cur.execute(query, (post_id,))
        row = cur.fetchone()

        # TODO: Преобразовать результат в объект Post, если строка найдена
        if row is not None:
            return Post(**row)
        return None


def get_feed(
    conn: connection, user_id: int = None, post_id: int = None, limit: int = 10
) -> List[Feed]:
    """
    Получает список действий пользователей с постами, включая данные о пользователях и постах.

    - Необходимо указать хотя бы один фильтр: user_id или post_id.
    - Возвращает не более `limit` записей.
    - Действия сортируются по времени: от самых свежих к более старым.
    - Используется для получения последних активностей пользователя или взаимодействий с постом.
    """
    if user_id is None and post_id is None:
        raise ValueError("Необходимо указать хотя бы user_id или post_id")
    # TODO: Написать SQL-запрос:
    # - выбрать данные из feed_action
    # - JOIN с user и post
    # - фильтрация по user_id / post_id (если заданы)
    # - сортировка по времени (DESC)
    # - ограничение по LIMIT

    #Ниже реализация фильтрации по user_id / post_id
    params = []
    where_parts = []

    if user_id is not None:
        #Если user_id задан (не None), добавляем в where_parts строку "fa.user_id = %s"
        where_parts.append("fa.user_id = %s") #В params кладём само значение user_id — оно позже подставится вместо %s
        params.append(user_id)

    if post_id is not None:
        where_parts.append("fa.post_id = %s")
        params.append(post_id)

    where_clause = " AND ".join(where_parts) #join() склеивает элементы where_parts через " AND "
    if where_clause:
        where_clause = "WHERE " + where_clause

    # f используем из-за того, что присутствует {where_clause}
    query = f"""
        SELECT fa.user_id,fa.post_id,u.id AS user_id, u.gender, u.age, u.country, u.city, u.exp_group, u.os, u.source,p.id AS post_id, p.text, p.topic,fa.action,fa.time
        FROM public.feed_action fa
        JOIN public.user u ON fa.user_id = u.id
        JOIN public.post p ON fa.post_id = p.id
        {where_clause}
        ORDER BY fa.time DESC
        LIMIT %s



        """
    params.append(limit)
    result = []
    with conn.cursor(cursor_factory=DictCursor) as cur:
        # TODO: Выполнить запрос, получить строки
        # TODO: Для каждой строки:
        # TODO: Создать объект User из строки
        # TODO: Создать объект Post из строки
        # TODO: Создать объект Feed и добавить в список result
        cur.execute(query, params)
        rows = cur.fetchall()

        for row in rows:
            # Создаём объект User из данных пользователя
            user = User(
                id=row['user_id'],
                gender=row['gender'],
                age=row['age'],
                country=row['country'],
                city=row['city'],
                exp_group=row['exp_group'],
                os=row['os'],
                source=row['source']
            )

            # Создаём объект Post из данных поста
            post = Post(
                id=row['post_id'],
                text=row['text'],
                topic=row['topic']
            )

            # Создаём объект Feed и добавляем в результат
            feed = Feed(
                user_id=row['user_id'],
                post_id=row['post_id'],
                user=user,
                post=post,
                action=row['action'],
                time=row['time']
            )
            result.append(feed)

    return result


def get_recommended_feed(conn: connection, id: int, limit: int) -> List[Post]:
    """
    Возвращает список top-N постов с наибольшим числом лайков.

    Это базовая реализация рекомендательной системы (baseline),
    которая не учитывает индивидуальные предпочтения, а показывает
    одинаковые популярные посты всем пользователям.

    Параметры:
        conn (connection): подключение к базе данных.
        id (int): ID пользователя (в этой версии не используется,
                  но оставлен для совместимости с будущей логикой).
        limit (int): количество постов в выдаче.

    Возвращает:
        List[Post]: список объектов Post, отсортированных по убыванию популярности.
    """
    # TODO: Написать SQL-запрос для выбора top-N постов с наибольшим числом лайков
    query = """
        SELECT p.id, p.text, p.topic
        FROM public.post p
        JOIN public.feed_action fa ON p.id = fa.post_id
        WHERE fa.action = 'like'
        GROUP BY p.id
        ORDER BY COUNT(fa.action) DESC
        LIMIT %s
    """

    with conn.cursor(cursor_factory=DictCursor) as cur:
        cur.execute(query, (limit,))
        rows = cur.fetchall()

        # TODO: Преобразовать строки в список объектов Post
        return [Post(
        id=row['id'],
        text=row['text'],
        topic=row['topic']
    ) for row in rows]