# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AI-C_lrHe-VTJwGGHA_IMh3Lav84HWBK
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional

@dataclass
class User:
    """
    Класс для представления пользователя.

    Атрибуты:
        id (int): Уникальный идентификатор пользователя.
        gender (int): Пол пользователя. (0 — мужчина, 1 — женщина).
        age (int): Возраст пользователя.
        country (str): Страна проживания пользователя.
        city (str): Город проживания пользователя.
        exp_group (int): Экспериментальная группа
        os (str): Операционная система устройства
        source (str): Источник трафика
    """
    id: int
    gender: int
    age: int
    country: str
    city: str
    exp_group: int
    os: str
    source: str


@dataclass
class Post:
    """
    Класс для представления поста (контента).

    Атрибуты:
        id (int): Уникальный идентификатор поста.
        text (str): Текст поста.
        topic (Optional[str], по умолчанию None): Тематика поста.
            Может быть None, если тема не задана.
    """
    id: int
    text: str
    topic: Optional[str] = None #Optional[str] означает, что переменная может быть строкой (str) или None.

@dataclass
class Feed:
    """
    Класс для представления действия пользователя с постом.

    Атрибуты:
        user_id (int): Идентификатор пользователя, совершившего действие.
        post_id (int): Идентификатор поста, с которым было совершено действие.
        user (User): Объект пользователя, совершившего действие.
        post (Post): Объект поста, с которым было совершено действие.
        action (str): Тип действия ('like', 'view').
        time (datetime): Время совершения действия.
    """
    user_id: int
    post_id: int
    user: User
    post: Post
    action: str
    time: datetime