# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rd7r0K4Y_giUa1OJzsNIWiapz_tG9_Wq
"""

import os
import pickle
from datetime import datetime
from typing import List
import numpy as np
import pandas as pd
from fastapi import FastAPI
from pydantic import BaseModel
from loguru import logger
from sqlalchemy import create_engine

# === Схемы ответов ===
class PostGet(BaseModel):
    id: int
    text: str
    topic: str

    class Config:
        orm_mode = True

# === Настройка подключения к базе данных ===
DATABASE_URL = "postgresql://robot-startml-ro:pheiph0hahj1Vaif@postgres.lab.karpov.courses:6432/startml"
engine = create_engine(DATABASE_URL)

def load_sql(query: str) -> pd.DataFrame:
    with engine.connect() as conn:
        try:
            df = pd.read_sql(query, conn)
        except Exception as e:
            raise RuntimeError(f" Ошибка при выполнении SQL-запроса: {e}\nЗапрос: {query}") from e
    return df

def load_model(model_path: str = "model.pkl"):
    if os.environ.get("IS_LMS", "0") == "1":
        model_path = os.environ["MODEL_PATH"]
    logger.info(f"Загрузка модели из файла {model_path}...")
    try:
        with open(model_path, "rb") as file:
            model = pickle.load(file)
    except FileNotFoundError:
        raise FileNotFoundError(f" Файл модели не найден: {model_path}")
    except Exception as e:
        raise RuntimeError(f" Ошибка при загрузке модели: {e}") from e
    logger.success("Модель успешно загружена")
    return model

# === Загрузка основных ресурсов ===
logger.info("Подготовка популярных постов для холодного старта...")
try:
    popular_posts_df = load_sql("""
        SELECT post_id, COUNT(*) as likes
        FROM public.feed_data
        WHERE action = 'like'
        GROUP BY post_id
        ORDER BY likes DESC
        LIMIT 20
    """)
    top_popular_ids = popular_posts_df['post_id'].tolist()
except Exception:
    top_popular_ids = [12, 45, 67, 89, 101, 234, 505, 607, 708, 809]

app = FastAPI()
model = load_model()

# Скачиваем базовые фичи пользователей из public.user_data и объединяем с  кастомными фичами
logger.info("Загрузка и объединение признаков пользователей...")
base_user_df = load_sql("SELECT user_id, gender, age, country, city, exp_group, os, source FROM public.user_data")
custom_user_df = load_sql("SELECT * FROM andr_iv7_user_features")

user_features = pd.merge(base_user_df, custom_user_df, on='user_id', how='left')

# Признаки постов
post_features = load_sql("SELECT * FROM andr_iv7_posts_info_features_dl")
if 'index' in post_features.columns:
    post_features.drop(['index'], axis=1, inplace=True)

# Тексты постов
post_texts = load_sql("SELECT post_id, text, topic FROM post_text_df").set_index('post_id')

logger.success("Сервис успешно инициализирован")

@app.get("/post/recommendations/", response_model=List[PostGet])
def recommended_posts(user_id: int, dt: datetime, limit: int = 10) -> List[PostGet]:

    # 1. Холодный старт
    if user_id not in user_features['user_id'].values:
        logger.info(f"Холодный старт для пользователя {user_id}. Отдаем популярное.")
        recs = []
        for post_id in top_popular_ids[:limit]:
            if post_id in post_texts.index:
                text_row = post_texts.loc[post_id]
                recs.append(PostGet(id=post_id, text=text_row['text'], topic=text_row['topic']))
        return recs

    # 2. Вытаскиваем фичи пользователя в виде словаря (одна строка)
    user_row = user_features[user_features['user_id'] == user_id].iloc[0].to_dict()

    # 3. Добавляем временные фичи прямо в этот словарь под именами из обучения
    user_row['hour'] = dt.hour
    user_row['month'] = dt.month

    # Удаляем из словаря user_id, так как в саму модель при обучении он не шел
    if 'user_id' in user_row:
        del user_row['user_id']

    # 4. Моделируем конвейер данных из обучения (размножаем фичи пользователя на все строки постов)
    feed_data_sim = post_features.copy()
    for col, val in user_row.items():
        feed_data_sim[col] = val  # Передаем скалярное значение, Pandas размножит его автоматически

    # 5. Идеальный жесткий порядок колонок, в точности соответствующий структуре модели CatBoost
    final_cols_order = [
        'hour', 'month', 'gender', 'age', 'country', 'city', 'exp_group', 'os', 'source',
        'topic', 'TextCluster',
        'DistanceToCluster_0', 'DistanceToCluster_1', 'DistanceToCluster_2', 'DistanceToCluster_3',
        'DistanceToCluster_4', 'DistanceToCluster_5', 'DistanceToCluster_6', 'DistanceToCluster_7',
        'DistanceToCluster_8', 'DistanceToCluster_9', 'DistanceToCluster_10', 'DistanceToCluster_11',
        'DistanceToCluster_12', 'DistanceToCluster_13', 'DistanceToCluster_14'
    ]

    # Заполняем пропуски нулями, если вдруг какая-то колонка отсутствует в сессии БД
    for col in final_cols_order:
        if col not in feed_data_sim.columns:
            feed_data_sim[col] = 0

    X = feed_data_sim[final_cols_order].copy()

    # 6. Приведение категориальных признаков к строковому типу (как в object_cols)
    cat_cols = ['topic', 'TextCluster', 'gender', 'country', 'city', 'exp_group', 'hour', 'month', 'os', 'source']
    for col in cat_cols:
        if col in X.columns:
            X[col] = X[col].astype(str).str.replace(r'\.0$', '', regex=True)

    # 7. Расчет вероятностей лайка через CatBoost
    proba = model.predict_proba(X)[:, 1]

    # Записываем вероятности обратно в исходную симуляцию, где сохранен post_id
    feed_data_sim['proba'] = proba

    # 8. Отбор лучших рекомендаций по вероятности
    top_posts = feed_data_sim.nlargest(limit, 'proba')

    # 9. Сборка ответа с текстами
    recs = []
    for _, row in top_posts.iterrows():
        post_id = int(row['post_id'])
        if post_id in post_texts.index:
            text_row = post_texts.loc[post_id]
            recs.append(PostGet(id=post_id, text=text_row['text'], topic=text_row['topic']))

    return recs