# -*- coding: utf-8 -*-
"""Финальный проект часть 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7bWaSFaMR3Tl363xcuy6zy76BlomPFR
"""

! pip3 install psycopg2-binary

#Это была установка библиотеки, которая связывает postgresql и python

#Создаём движок подключение к PostqreSQL

from sqlalchemy import create_engine


engine = create_engine("postgresql://robot-startml-ro:pheiph0hahj1Vaif@postgres.lab.karpov.courses:6432/startml")

connection = engine.connect().execution_options(stream_results=True)

#Перейдем теперь к загрузке постов из postgresql в наш датафрейм

### Посты и топики
### С постами придется повозиться, сгенерируем эмбеддинги постов с помощью моделей из 10 занятия
import pandas as pd


posts_info = pd.read_sql(
    """SELECT * FROM public.post_text_df""",
    con=connection
)

posts_info

### Сделаем эмбеддинги постов с помощью моделей трансформера

from transformers import AutoTokenizer
from transformers import BertModel  # https://huggingface.co/docs/transformers/model_doc/bert#transformers.BertModel
from transformers import RobertaModel  # https://huggingface.co/docs/transformers/model_doc/roberta#transformers.RobertaModel
from transformers import DistilBertModel  # https://huggingface.co/docs/transformers/model_doc/distilbert#transformers.DistilBertModel


def get_model(model_name):
    assert model_name in ['bert', 'roberta', 'distilbert'] # проверяем, есть ли переданное имя нейросети среди этих моделей

    # создаем словарь, ключ - имя нейросети, значение - чекпоинт нейросети
    checkpoint_names = {
        'bert': 'bert-base-cased',  # https://huggingface.co/bert-base-cased
        'roberta': 'roberta-base',  # https://huggingface.co/roberta-base
        'distilbert': 'distilbert-base-cased'  # https://huggingface.co/distilbert-base-cased
    }
    # создаем словарь, ключ - имя нейросети, значение - чекпоинт нейросети
    model_classes = {
        'bert': BertModel,
        'roberta': RobertaModel,
        'distilbert': DistilBertModel
    }

    # возвращаем токенизатор через чекпоинт нейросети, саму модель через чекпоинт нейросети
    return AutoTokenizer.from_pretrained(checkpoint_names[model_name]), model_classes[model_name].from_pretrained(checkpoint_names[model_name])

# Вызываем эту функцию и создаем токенизатор и модель 'distilbert'

tokenizer, model = get_model('distilbert')

# Теперь сделаем датасет для постов

from torch.utils.data import Dataset # пустой шаблон
from torch.utils.data import DataLoader # хранит батчи
from transformers import DataCollatorWithPadding # автоматический упаковщик до максимальной длины одного из постов (добавляет нули к коротким текстам внутри одной пачки)


# Создаём хранилище, внутри которого прописываем правила для работы с данными
class PostDataset(Dataset):
    def __init__(self, texts, tokenizer): # подготовка при создании
        super().__init__() # запускает настройки родительского класса Dataset

        self.texts = tokenizer( # токенизатор для обратбоки целого списка текстов
            texts, # наши сырые тексты
            add_special_tokens=True, # служебные маркеры начала и конца текста специально для моделей BERT семейства
            return_token_type_ids=False, # отключает маски типов токенов (для наших постов она не нужна, только для пару предложений)
            return_tensors='pt', # возвращает результат в виде готовых тензоров матриц
            truncation=True, # умная обрезка текстов (обычно 512 токенов), защита от критической ошибки
            padding=True # предварительное выравнивание
        )
        self.tokenizer = tokenizer # записываем объект токенизатора во внутреннюю память класса

    def __getitem__(self, idx): # этот метод учить программу вовзращать две пары ключ-значение
        return {
            'input_ids': self.texts['input_ids'][idx], # зашифрованный текст поста
            'attention_mask': self.texts['attention_mask'][idx] # карта-подсказка для нейросети, которая содержит важность(вес) каждого слова в посте
            }

    def __len__(self):
        return len(self.texts['input_ids']) # общее количество постов в нашем наборе данных


dataset = PostDataset(posts_info['text'].values.tolist(), tokenizer)
# posts_info['text'] - вытаскивает колонку с сырыми текстами постов из таблицы Pandas.
# .values.tolist() - превращает эту колонку в обычный плоский список строк (Python list), так как наш класс ожидает именно его
# tokenizer - передает созданный ранее токенизатор distilbert

data_collator = DataCollatorWithPadding(tokenizer=tokenizer) # паддинг коротких постов до длины максимального поста именно в этом батче

loader = DataLoader(dataset, batch_size=32, collate_fn=data_collator, pin_memory=True, shuffle=False)

# dataset - передаем наше хранилище данных, откуда нужно брать посты
# batch_size=32 - указывает выдавать данные пачками (батчами) ровно по 32 штуки за один шаг
# collate_fn=data_collator -  подключает созданный строкой выше упаковщик, чтобы пачки внутри были ровными матрицами
# pin_memory=True - техническая команда для ускорения обучения
# shuffle=False - отключает перемешивание постов

import torch # импорт библиотеки PyTorch
from tqdm import tqdm # импорт визуального индикатора прогресса


@torch.inference_mode() # заморозка нейросети (отключение вычиссления градиентов)
def get_embeddings_labels(model, loader): # принимаем на вход функции саму модель и подготовленный конвейер данных
    model.eval() # переводим в режим оценки нашу модель

    total_embeddings = [] # список с эмбеддингами

    for batch in tqdm(loader): # tqdm берет конвейер и начинает выдавать из него данные пачками по 32 поста за раз
        batch = {key: batch[key].to(device) for key in ['attention_mask', 'input_ids']} # переносит данные из оперативной памяти компьютера в память видеокарты

        embeddings = model(**batch)['last_hidden_state'][:, 0, :]
        # model(**batch) - здесь мы распаковываем словарь батч, в котором есть две коробки: 'attention_mask', 'input_ids'
        # ['last_hidden_state'] - здесь мы по ключу достаем матрицу (последнее скрытое состояние) - выход из последнего слоя нейросети
        # [:, 0, :] - : - взять абсолютно все посты, 0 - из каждого поста берем только первое слово (служебный маркер CLS, в котором заложен контекст всего поста), : - взять все 768 чисел характеристики для токена CLS
        total_embeddings.append(embeddings.cpu()) # соответственно добавляем готовые эмбеддинги в список с эмбеддингами с ЦПУ

    return torch.cat(total_embeddings, dim=0) # берем и склеиваем все наши эмбеддинги со всех батчей по вертикали

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

# присваиваем видеокарту системе

print(device)
print(torch.cuda.get_device_name())

model = model.to(device) # загрузка модели на видеокарту

embeddings = get_embeddings_labels(model, loader).numpy()
# получаем наш тензор эмбеддингов и преобразуем в массив numpy

embeddings

### Пытаемся кластеризовать тексты

from sklearn.decomposition import PCA # метод главных компонент - ищет скрытые связи и схлопывает сотни признаков в дестяки информативных

centered = embeddings - embeddings.mean() # из каждого числа в в матрице вычитается среднее из всей матрицы

pca = PCA(n_components=50) # ужимаем размер эмбеддинга с 768 чисел до 50
pca_decomp = pca.fit_transform(centered) # трансформация матрицы centered

from sklearn.cluster import KMeans # импортиркем алгоритм ближайших соседей

n_clusters = 15 # задаем количество кластеров

# создаем объект алгоритма, random_state=0 нужен для того, чтобы при каждом перезапуске ячейки посты делились на группы абсолютно одинаково
#.fit(pca_decomp) запускает процесс кластеризации
kmeans = KMeans(n_clusters=n_clusters, random_state=0).fit(pca_decomp)

# в таблице постов создается новая колонка 'TextCluster', у которой значение соответствует номеру кластера для каждого поста
posts_info['TextCluster'] = kmeans.labels_

# создаем будущие колонки таблицы постов с номера кластеров 'DistanceToCluster_0', 'DistanceToCluster_1', ...,
dists_columns = [f'DistanceToCluster_{i}' for i in range(n_clusters)]

#
dists_df = pd.DataFrame( # наша новая таблица расстояний (вместо самих номеров кластеров)
    data=kmeans.transform(pca_decomp), # этот метод считает физическое расстояние от каждого поста до центра каждого кластера
    columns=dists_columns # созданные выше колонки
)

dists_df.head()

posts_info = pd.concat((posts_info, dists_df), axis=1) # склеиваем по горизонтали исходную таблицу с новой таблицой расстояний

posts_info.drop(["text"], axis=1, inplace=True) # удаляем колонку текст из таблицы, inplace=True - прямо в текущей переменной

posts_info

### Очищаем память чтобы все влезло

model.cpu() # принудительно выгружает модель из памяти видеокарты обратно в обычную память процессора

# удаляем модель и токенизатор
del model
del tokenizer

# удаляем конвейер данных и обертку над текстами
del dataset
del loader

# удаляем эмбеддинги, центрированную матрицу, объект алгоритма PCA, сжатую 50-мерную матрицу
del embeddings
del centered
del pca
del pca_decomp

import gc

gc.collect() # команда жесткой очистки в оперативной памяти

posts_info.to_sql( # отправляем и сохраняем таблицу в базу данных postgresql
   "andr_iv7_posts_info_features_dl", #  название таблицы
    con="postgresql://robot-startml-ro:pheiph0hahj1Vaif@postgres.lab.karpov.courses:6432/startml", # строка подключения к серверу
    schema="public", # общая схема подключения
    if_exists='replace' # если уже есть таблица с таким названием, полностью удаляется и перезаписывается
)

# Приступаем к обработке действий

### Попробуем забрать, скажем, 9 миллионов, сразу очистим и оставим только view


feed_data = pd.read_sql(
    #cast(extract(hour from timestamp) as int) as hour - Извлекает час (от 0 до 23) из полной даты и времени события (timestamp), превращает его в целое число (int) и переименовывает эту новую колонку в hour. Это нужно для учета времени суток в рекомендациях
    #cast(extract(month from timestamp) as int) as month - Точно так же извлекает номер месяца (от 1 до 12) из даты, переводит в число и называет колонку month (для учета сезонности)
    #FROM public.feed_data JOIN public.user_data ON public.feed_data.user_id = public.user_data.user_id - склейка таблицы активностей и пользователей по user_id
   # WHERE action = 'view' - берет активность только просмотр,  без лайков
    #LIMIT 9000000 - берем только первые 9000000 строк

    """
    SELECT
        cast(extract(hour from timestamp) as int) as hour,
        cast(extract(month from timestamp) as int) as month,
        post_id,
        gender,
        age,
        country,
        city,
        exp_group,
        os,
        source,
        target
    FROM public.feed_data JOIN public.user_data ON public.feed_data.user_id = public.user_data.user_id
    WHERE action = 'view'
    LIMIT 9000000
    """,
    con=connection
)

feed_data.head()

!pip install catboost

from catboost import CatBoostClassifier, Pool # CatBoostClassifier - модель классификации от Яндекса, Pool — импортирует специальный внутренний формат данных CatBoost для эффективного хранения признаков
from tqdm import tqdm


object_cols = [
    'topic', 'TextCluster', 'gender', 'country',
    'city', 'exp_group', 'hour', 'month',
    'os', 'source'
] # список категориальных признаков
#Алгоритм CatBoost уникален тем, что умеет работать с текстом и категориями напрямую (без ручного перевода в числа вроде One-Hot Encoding).
#Ему нужно просто передать этот список, и он сам зашифрует данные внутри своих алгоритмов.

catboost = CatBoostClassifier(
    iterations=200, # количество деревьев решений в ансамбле
    learning_rate=1, # скорость обучения - шаг градиентного спуска
    depth=2, # глубина деревьев
    random_seed=12345612, # генератор случайных чисел (для идентичности результатов при повторном запуске ячейки)
    thread_count=-1, # Заставляет задействовать абсолютно все доступные ядра процессора для подготовки данных и параллельных вычислений.
    task_type="GPU" # обучение на видеокарте, а не на процессоре
)

feed_data = pd.merge(
    feed_data,
    posts_info,
    on='post_id',
    how='left' # левое присоединение
)

feed_data.drop(['post_id'], axis=1, inplace=True) #  Уникальный номер поста (просто id в базе) — это не признак, он не несет в себе паттернов для предсказания и будет только путать модель при ветвлении деревьев.

catboost.fit(X=feed_data.drop(['target'], axis=1), y=feed_data['target'], cat_features=object_cols) # обучение модели с передачей ей при

catboost.save_model(
    'catboost_model.cbm',
    format="cbm"
)

import pickle

# Сохраняем модель CatBoost через стандартный pickle
with open('model.pkl', 'wb') as f:
    pickle.dump(catboost, f)

